BlogCore/BlogCore/Areas/Admin/Controllers/ArticulosController.cs
using BlogCore.AccesoDatos.Data.Repository.IRepository;
using BlogCore.Data;
using BlogCore.Models;
using BlogCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Admin.Controllers
{
    [Area("Admin")] //importante agregar el area 
    public class ArticulosController : Controller
    { //en vez de usar el contexto de usa el contenedor de trabajo
        private readonly IContenedorTrabajo _contenedorTrabajo;
        private readonly ApplicationDbContext _context;
        public ArticulosController(IContenedorTrabajo contenedorTrabajo, ApplicationDbContext context)
        {
            _contenedorTrabajo = contenedorTrabajo;
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            ArticuloVM articuloVM = new ArticuloVM() { 
                Articulo= new Articulo(),
                ListaCategorias= _contenedorTrabajo.Categoria.GetListaCategorias()
            };
            return View(articuloVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Articulo articulo)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Articulo.Add(articulo);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            //si el modelo tiene algun error devuelvo a la vista los mismos datos del modelo.
            return View(articulo);
        }

        #region llamadas a la api
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Articulo.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            Articulo objFromDb = new Articulo();
            objFromDb = _contenedorTrabajo.Articulo.Get(id);
            if (objFromDb == null)
            {
                return Json(new { succes = false, message = "Error borrado Articulo" });
            }
            _contenedorTrabajo.Articulo.Remove(objFromDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Borrado con Exito" });
        }
        #endregion
    }
}

BlogCore/BlogCore/Areas/Admin/Controllers/CategoriasController.cs
using BlogCore.AccesoDatos.Data.Repository.IRepository;
using BlogCore.Data;
using BlogCore.Models;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriasController : Controller
    {
        //en vez de usar el contexto de usa el contenedor de trabajo
        private readonly IContenedorTrabajo _contenedorTrabajo;
        private readonly ApplicationDbContext _context;
        public CategoriasController(IContenedorTrabajo contenedorTrabajo,ApplicationDbContext context)
        {
            _contenedorTrabajo = contenedorTrabajo;
            _context= context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Categoria.Add(categoria);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Categoria categoria = new Categoria();
            categoria = _contenedorTrabajo.Categoria.Get(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Categoria.Update(categoria);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

       

        #region llamadas a la api
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Categoria.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            Categoria objFromDb = new Categoria();
            objFromDb = _contenedorTrabajo.Categoria.Get(id);
            if (objFromDb == null) {
                return Json(new { succes = false, message = "Error borrado categoría" });
            }
            _contenedorTrabajo.Categoria.Remove(objFromDb);
            _contenedorTrabajo.Save();
            return Json(new {success=true,message="Borrado con Exito"});
        }
        #endregion
    }
}

BlogCore/BlogCore/Areas/Cliente/Controllers/HomeController.cs
using BlogCore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogCore.Areas.Cliente.Controllers
{
    [Area("Cliente")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogCore/BlogCore/Controllers/HomeController.cs
using BlogCore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogCore/BlogCore/Areas/Admin/Views/Articulos/Create.cshtml
@model BlogCore.Models.ViewModels.ArticuloVM
@{
    ViewData["Title"] = "Crear Artículo";
}
<br />
<br />
<h3 class="text-center">Crear un Artículo</h3>
<form method="post" asp-action="Create">
    <div class="row px-2 offset-1 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-10 offset-1 mt-4">
            <div class="form-group row">
                <div class="col-5">
                    <label class="col-6">
                        <label asp-for="Articulo.Nombre"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Articulo.Nombre" class="form-control" placeholder="Ingrese nombre del Artículo" />
                    <span asp-validation-for="Articulo.Nombre" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-5">
                    <label class="col-6">
                        <label asp-for="Articulo.Descripcion"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Articulo.Descripcion" class="form-control" placeholder="Ingrese la Descripcion del Artículo" />
                    <span asp-validation-for="Articulo.Descripcion" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-5">
                    <label class="col-6">
                        <label >Categoria:</label>
                    </label>
                </div>
                <div class="col-7">
                   @Html.DropDownListFor(m=> m.Articulo.CategoriaId,Model.ListaCategorias,"-Por favor selccione una categoría",new {@class="form-control"})
                    
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8">
                    <partial name="_VistaCrearVolver" />
                </div>
            </div>
        </div>

    </div>
</form>

BlogCore/BlogCore/Areas/Admin/Views/Articulos/Index.cshtml
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2 class="text-primary">Lista de Articulos</h2>
        </div>
        <div class="col-4">
            <a asp-action="Create" class="btn btn-primary"><i class="fas fa-plus"></i>Crear Un Artículo</a>
        </div>
    </div>
    <br />
    <br />
    <table id="tblArticulos" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Descripcíon</th>
                <th>Fecha de creacion</th>
                <th>Acciones</th>
            </tr>
        </thead>

    </table>
</div>

@section Scripts {
    <script src="~/js/articulo.js"></script>
}

BlogCore/BlogCore/Areas/Admin/Views/Categorias/Create.cshtml
@model BlogCore.Models.Categoria
@{
    ViewData["Title"] = "Crear Categoría";
}
<br />
<br />
<h3 class="text-center">Crear una nueva Categoría</h3>
<form method="post" asp-action="Create">
    <div class="row px-2 offset-1 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-10 offset-1 mt-4">
            <div class="form-group row">
                <div class="col-5">
                    <label class="col-6">
                        <label asp-for="Nombre"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Nombre" class="form-control" placeholder="Ingrese nombre de Categoría"/>
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-5">
                    <label class="col-6">
                        <label asp-for="Orden"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Orden" class="form-control" placeholder="Ingrese Orden de Categoría"/>
                    <span asp-validation-for="Orden" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8">
                    <partial name="_VistaCrearVolver" />
                </div>
            </div>
        </div>
        
    </div>
</form>

BlogCore/BlogCore/Areas/Admin/Views/Categorias/Edit.cshtml
@model BlogCore.Models.Categoria
@{
    ViewData["Title"] = "Editar Categoría";
}
<br />
<br />
<h3 class="text-center">Editar Categoría</h3>
<form method="post" asp-action="Edit">
    <div class="row px-2 offset-1 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-10 offset-1 mt-4">
            <div class="form-group row">
                <div class="col-5">
                    <label class="col-6">
                        <label asp-for="Nombre"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Nombre" class="form-control" placeholder="Ingrese nombre de Categoría" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-5">
                    <label class="col-6">
                        <label asp-for="Orden"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Orden" class="form-control" placeholder="Ingrese Orden de Categoría" />
                    <span asp-validation-for="Orden" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col">
                   <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model.Id">Actualizar</button>
                </div>
                <div class="col">
                    <a asp-action="Index" class="btn btn-success form-control">Volver a Lista</a>
                </div>
            </div>
        </div>

    </div>
</form>

BlogCore/BlogCore/Areas/Admin/Views/Categorias/Index.cshtml
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2 class="text-primary">Lista de Categorias</h2>
        </div>
        <div class="col-4">
            <a asp-action="Create" class="btn btn-primary"><i class="fas fa-plus"></i>Crear Nueva Categoria</a>
        </div>
    </div>
    <br />
    <br />
    <table id="tblCategorias" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Orden</th>
                <th>Acciones</th>
            </tr>
        </thead>

    </table>
</div>

@section Scripts {
    <script src="~/js/categoria.js" ></script>
}

BlogCore/BlogCore/Areas/Cliente/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BlogCore/BlogCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogCore.styles.css" asp-append-version="true" />

    <!--plugin frontend-->
    
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="Cliente" asp-controller="Home" asp-action="Index">Blog Core</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                       
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Contenidos</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Categorias" asp-action="Index">Categorías</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Articulos" asp-action="Index">Artículos</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Sliders" asp-action="Index">Categorías</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                            </div>
                        </li>
                    </ul>                    
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BlogCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/0f48d8c00d.js" crossorigin="anonymous"></script>
   
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogCore/BlogCore/Views/Shared/_VistaCrearVolver.cshtml
<div class="row mt-2  align-content-center">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Crear</button>
    </div>
    &nbsp;
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Volver a Lista</a> 
    </div>
</div>